{{- if and .Values.deploy.applicationProperties.enabled (eq .Values.deploy.applicationProperties.type "ConfigMap") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dotnet.name" . }}
  labels:
    {{- include "dotnet.labels" . | nindent 4 }}
data:
  appsettings.json: |-
    {{- tpl .Values.deploy.applicationProperties.properties . | nindent 4 }}
{{- end }}