{{- if and .Values.deploy.applicationProperties.enabled (eq .Values.deploy.applicationProperties.type "Secret") }}
kind: Secret 
apiVersion: v1 
metadata:
  name: {{ include "dotnet.name" . }}
  labels:
    {{- include "dotnet.labels" . | nindent 4 }}
stringData: 
  appsettings.json: |-
    {{- tpl .Values.deploy.applicationProperties.properties . | nindent 4 }}
type: Opaque 
{{- end }}