apiVersion: v1
kind: Service
metadata:
  name: {{ include "dotnet.name" . }}
  labels:
    {{- include "dotnet.labels" . | nindent 4 }}
    monitorint: "false"
spec:
  selector:
    {{- include "dotnet.selectorLabels" . | nindent 4 }}
  ports:
    {{- tpl (toYaml .Values.deploy.ports) . | nindent 4 }}
  type: ClusterIP
  sessionAffinity: None    